/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopHeadlinesCategoryRouteImport } from './routes/top-headlines.$category'
import { Route as SearchQueryRouteImport } from './routes/search.$query'
import { Route as CountryIsoRouteImport } from './routes/country.$iso'
import { Route as ApiWeatherRouteImport } from './routes/api/weather'
import { Route as ApiTopHeadlinesRouteImport } from './routes/api/top-headlines'
import { Route as ApiAllNewsRouteImport } from './routes/api/all-news'
import { Route as ApiSearchMsgRouteImport } from './routes/api/search.msg'
import { Route as ApiCountryIsoRouteImport } from './routes/api/country.$iso'

const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopHeadlinesCategoryRoute = TopHeadlinesCategoryRouteImport.update({
  id: '/top-headlines/$category',
  path: '/top-headlines/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchQueryRoute = SearchQueryRouteImport.update({
  id: '/search/$query',
  path: '/search/$query',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryIsoRoute = CountryIsoRouteImport.update({
  id: '/country/$iso',
  path: '/country/$iso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTopHeadlinesRoute = ApiTopHeadlinesRouteImport.update({
  id: '/api/top-headlines',
  path: '/api/top-headlines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAllNewsRoute = ApiAllNewsRouteImport.update({
  id: '/api/all-news',
  path: '/api/all-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchMsgRoute = ApiSearchMsgRouteImport.update({
  id: '/api/search/msg',
  path: '/api/search/msg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountryIsoRoute = ApiCountryIsoRouteImport.update({
  id: '/api/country/$iso',
  path: '/api/country/$iso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/history': typeof HistoryRoute
  '/api/all-news': typeof ApiAllNewsRoute
  '/api/top-headlines': typeof ApiTopHeadlinesRoute
  '/api/weather': typeof ApiWeatherRoute
  '/country/$iso': typeof CountryIsoRoute
  '/search/$query': typeof SearchQueryRoute
  '/top-headlines/$category': typeof TopHeadlinesCategoryRoute
  '/api/country/$iso': typeof ApiCountryIsoRoute
  '/api/search/msg': typeof ApiSearchMsgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/history': typeof HistoryRoute
  '/api/all-news': typeof ApiAllNewsRoute
  '/api/top-headlines': typeof ApiTopHeadlinesRoute
  '/api/weather': typeof ApiWeatherRoute
  '/country/$iso': typeof CountryIsoRoute
  '/search/$query': typeof SearchQueryRoute
  '/top-headlines/$category': typeof TopHeadlinesCategoryRoute
  '/api/country/$iso': typeof ApiCountryIsoRoute
  '/api/search/msg': typeof ApiSearchMsgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookmarks': typeof BookmarksRoute
  '/history': typeof HistoryRoute
  '/api/all-news': typeof ApiAllNewsRoute
  '/api/top-headlines': typeof ApiTopHeadlinesRoute
  '/api/weather': typeof ApiWeatherRoute
  '/country/$iso': typeof CountryIsoRoute
  '/search/$query': typeof SearchQueryRoute
  '/top-headlines/$category': typeof TopHeadlinesCategoryRoute
  '/api/country/$iso': typeof ApiCountryIsoRoute
  '/api/search/msg': typeof ApiSearchMsgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookmarks'
    | '/history'
    | '/api/all-news'
    | '/api/top-headlines'
    | '/api/weather'
    | '/country/$iso'
    | '/search/$query'
    | '/top-headlines/$category'
    | '/api/country/$iso'
    | '/api/search/msg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookmarks'
    | '/history'
    | '/api/all-news'
    | '/api/top-headlines'
    | '/api/weather'
    | '/country/$iso'
    | '/search/$query'
    | '/top-headlines/$category'
    | '/api/country/$iso'
    | '/api/search/msg'
  id:
    | '__root__'
    | '/'
    | '/bookmarks'
    | '/history'
    | '/api/all-news'
    | '/api/top-headlines'
    | '/api/weather'
    | '/country/$iso'
    | '/search/$query'
    | '/top-headlines/$category'
    | '/api/country/$iso'
    | '/api/search/msg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookmarksRoute: typeof BookmarksRoute
  HistoryRoute: typeof HistoryRoute
  ApiAllNewsRoute: typeof ApiAllNewsRoute
  ApiTopHeadlinesRoute: typeof ApiTopHeadlinesRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  CountryIsoRoute: typeof CountryIsoRoute
  SearchQueryRoute: typeof SearchQueryRoute
  TopHeadlinesCategoryRoute: typeof TopHeadlinesCategoryRoute
  ApiCountryIsoRoute: typeof ApiCountryIsoRoute
  ApiSearchMsgRoute: typeof ApiSearchMsgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-headlines/$category': {
      id: '/top-headlines/$category'
      path: '/top-headlines/$category'
      fullPath: '/top-headlines/$category'
      preLoaderRoute: typeof TopHeadlinesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/$query': {
      id: '/search/$query'
      path: '/search/$query'
      fullPath: '/search/$query'
      preLoaderRoute: typeof SearchQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country/$iso': {
      id: '/country/$iso'
      path: '/country/$iso'
      fullPath: '/country/$iso'
      preLoaderRoute: typeof CountryIsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/top-headlines': {
      id: '/api/top-headlines'
      path: '/api/top-headlines'
      fullPath: '/api/top-headlines'
      preLoaderRoute: typeof ApiTopHeadlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/all-news': {
      id: '/api/all-news'
      path: '/api/all-news'
      fullPath: '/api/all-news'
      preLoaderRoute: typeof ApiAllNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search/msg': {
      id: '/api/search/msg'
      path: '/api/search/msg'
      fullPath: '/api/search/msg'
      preLoaderRoute: typeof ApiSearchMsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/country/$iso': {
      id: '/api/country/$iso'
      path: '/api/country/$iso'
      fullPath: '/api/country/$iso'
      preLoaderRoute: typeof ApiCountryIsoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookmarksRoute: BookmarksRoute,
  HistoryRoute: HistoryRoute,
  ApiAllNewsRoute: ApiAllNewsRoute,
  ApiTopHeadlinesRoute: ApiTopHeadlinesRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  CountryIsoRoute: CountryIsoRoute,
  SearchQueryRoute: SearchQueryRoute,
  TopHeadlinesCategoryRoute: TopHeadlinesCategoryRoute,
  ApiCountryIsoRoute: ApiCountryIsoRoute,
  ApiSearchMsgRoute: ApiSearchMsgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
